version: 2
test:
  - name: TIZEN_DEVICE_MLOPS_AGENT
    testCaseLanguage: CPP
    testFW: GTEST
    testCaseFolder:
      - ./tests/
  
    testFile:
      - extension: cc
        starts:
          - unittest
 
    testCase:
      - condition:
        - functionName:
            starts:
              - 'TEST'
 
    negativeTestCase:
      - condition:
        - testName:
            ends:
              - _n

    positiveTestCase:
      - condition:
        - inverse: negativeTestCase
